import type { Listing, Company } from '@/types'

export const mockCompanies: Company[] = [
  { id: '1', name: 'Stripe', logo_url: 'https://logo.clearbit.com/stripe.com', website: 'https://stripe.com', description: 'Financial infrastructure for the internet.', industry: 'Technology', created_at: '2024-01-01' },
  { id: '2', name: 'Deloitte', logo_url: 'https://logo.clearbit.com/deloitte.com', website: 'https://deloitte.com', description: 'Global professional services firm.', industry: 'Consulting', created_at: '2024-01-01' },
  { id: '3', name: 'NASA', logo_url: 'https://logo.clearbit.com/nasa.gov', website: 'https://nasa.gov', description: 'Pioneering the future in space exploration.', industry: 'Government', created_at: '2024-01-01' },
  { id: '4', name: 'Pfizer', logo_url: 'https://logo.clearbit.com/pfizer.com', website: 'https://pfizer.com', description: 'Global pharmaceutical leader.', industry: 'Healthcare', created_at: '2024-01-01' },
  { id: '5', name: 'Goldman Sachs', logo_url: 'https://logo.clearbit.com/goldmansachs.com', website: 'https://goldmansachs.com', description: 'Leading global investment banking firm.', industry: 'Finance', created_at: '2024-01-01' },
  { id: '6', name: 'ExxonMobil', logo_url: 'https://logo.clearbit.com/exxonmobil.com', website: 'https://exxonmobil.com', description: 'Global energy and petrochemical company.', industry: 'Energy', created_at: '2024-01-01' },
  { id: '7', name: 'McKinsey & Company', logo_url: 'https://logo.clearbit.com/mckinsey.com', website: 'https://mckinsey.com', description: 'Global management consulting firm.', industry: 'Consulting', created_at: '2024-01-01' },
  { id: '8', name: 'The New York Times', logo_url: 'https://logo.clearbit.com/nytimes.com', website: 'https://nytimes.com', description: 'Leading news organization and media company.', industry: 'Media', created_at: '2024-01-01' },
]

export const mockListings: Listing[] = [
  {
    id: '1', company_id: '1', title: 'Software Engineering Intern', type: 'internship',
    industry: 'Technology', location_type: 'hybrid', city: 'San Francisco', state: 'CA',
    pay_rate: 45, pay_period: 'hourly',
    description: 'Join Stripe\'s engineering team and work on real payment infrastructure used by millions of businesses worldwide. You\'ll be embedded in a product team, shipping code to production within your first week.\n\nOur interns tackle real problems alongside full-time engineers. Past intern projects include improvements to Stripe Dashboard, new developer tooling, and fraud detection algorithms.',
    requirements: 'Currently enrolled in a BS/MS in CS or related field. Experience with at least one of: Go, Ruby, Java, Scala, or JavaScript. Strong problem-solving skills.',
    apply_url: 'https://stripe.com/jobs', apply_email: null,
    deadline: '2025-03-15', tier: 'premium', is_featured: true, is_active: true, created_at: '2024-11-01',
    companies: { id: '1', name: 'Stripe', logo_url: 'https://logo.clearbit.com/stripe.com', website: 'https://stripe.com', description: 'Financial infrastructure for the internet.', industry: 'Technology', created_at: '2024-01-01' },
  },
  {
    id: '2', company_id: '2', title: 'Business Technology Analyst Intern', type: 'internship',
    industry: 'Consulting', location_type: 'on-site', city: 'New York', state: 'NY',
    pay_rate: 35, pay_period: 'hourly',
    description: 'Work alongside senior consultants to deliver technology solutions for Fortune 500 clients. Projects span cloud migration, data analytics, and digital transformation.\n\nAs an intern analyst, you\'ll contribute to every phase of an engagement — from initial discovery through implementation and change management.',
    requirements: 'Junior or Senior pursuing a degree in Business, CS, or Engineering. Strong analytical skills. GPA 3.2+.',
    apply_url: 'https://deloitte.com/careers', apply_email: null,
    deadline: '2025-02-28', tier: 'premium', is_featured: true, is_active: true, created_at: '2024-11-05',
    companies: { id: '2', name: 'Deloitte', logo_url: 'https://logo.clearbit.com/deloitte.com', website: 'https://deloitte.com', description: 'Global professional services firm.', industry: 'Consulting', created_at: '2024-01-01' },
  },
  {
    id: '3', company_id: '3', title: 'Aerospace Engineering Co-op', type: 'co-op',
    industry: 'Government', location_type: 'on-site', city: 'Houston', state: 'TX',
    pay_rate: 28, pay_period: 'hourly',
    description: 'Work on spacecraft design and mission planning at NASA Johnson Space Center. This 6-month co-op gives you hands-on experience with real flight hardware.\n\nYou\'ll be assigned to a specific project team — previous co-ops have contributed to the Artemis lunar program, ISS operations, and advanced spacecraft systems.',
    requirements: 'US Citizenship required. Enrolled in ABET-accredited Aerospace, Mechanical, or Electrical Engineering program. Min 3.0 GPA.',
    apply_url: 'https://nasa.gov/careers', apply_email: null,
    deadline: '2025-01-31', tier: 'standard', is_featured: false, is_active: true, created_at: '2024-10-20',
    companies: { id: '3', name: 'NASA', logo_url: 'https://logo.clearbit.com/nasa.gov', website: 'https://nasa.gov', description: 'Pioneering the future in space exploration.', industry: 'Government', created_at: '2024-01-01' },
  },
  {
    id: '4', company_id: '4', title: 'Pharmaceutical Research Intern', type: 'internship',
    industry: 'Healthcare', location_type: 'on-site', city: 'New York', state: 'NY',
    pay_rate: 7500, pay_period: 'monthly',
    description: 'Support clinical trial data analysis and regulatory submission preparation within our Global Medical Affairs team.',
    requirements: 'Pre-med, Pharmacy, Biology, or Chemistry major. Familiarity with clinical data and FDA submission processes a plus.',
    apply_url: 'https://pfizer.com/careers', apply_email: null,
    deadline: '2025-03-01', tier: 'standard', is_featured: false, is_active: true, created_at: '2024-11-10',
    companies: { id: '4', name: 'Pfizer', logo_url: 'https://logo.clearbit.com/pfizer.com', website: 'https://pfizer.com', description: 'Global pharmaceutical leader.', industry: 'Healthcare', created_at: '2024-01-01' },
  },
  {
    id: '5', company_id: '5', title: 'Investment Banking Summer Analyst', type: 'internship',
    industry: 'Finance', location_type: 'on-site', city: 'New York', state: 'NY',
    pay_rate: 110000, pay_period: 'monthly',
    description: 'Join our M&A or Capital Markets group for a 10-week program. Build financial models, prepare client materials, and participate in live deal teams.',
    requirements: 'Junior pursuing Finance, Economics, or related degree. Exceptional quantitative and communication skills.',
    apply_url: 'https://goldmansachs.com/careers', apply_email: null,
    deadline: '2024-12-15', tier: 'featured', is_featured: true, is_active: true, created_at: '2024-10-01',
    companies: { id: '5', name: 'Goldman Sachs', logo_url: 'https://logo.clearbit.com/goldmansachs.com', website: 'https://goldmansachs.com', description: 'Leading global investment banking firm.', industry: 'Finance', created_at: '2024-01-01' },
  },
  {
    id: '6', company_id: '6', title: 'Petroleum Engineering Co-op', type: 'co-op',
    industry: 'Energy', location_type: 'on-site', city: 'Houston', state: 'TX',
    pay_rate: 32, pay_period: 'hourly',
    description: 'Rotate through reservoir engineering, drilling, and production teams over 8 months. Gain exposure to both conventional and renewable energy projects.',
    requirements: 'Petroleum, Chemical, or Mechanical Engineering major. Must be eligible to work in the US.',
    apply_url: 'https://exxonmobil.com/careers', apply_email: null,
    deadline: '2025-02-01', tier: 'standard', is_featured: false, is_active: true, created_at: '2024-10-15',
    companies: { id: '6', name: 'ExxonMobil', logo_url: 'https://logo.clearbit.com/exxonmobil.com', website: 'https://exxonmobil.com', description: 'Global energy and petrochemical company.', industry: 'Energy', created_at: '2024-01-01' },
  },
  {
    id: '7', company_id: '7', title: 'Business Analyst Intern', type: 'internship',
    industry: 'Consulting', location_type: 'hybrid', city: 'Chicago', state: 'IL',
    pay_rate: 38, pay_period: 'hourly',
    description: 'Solve complex business problems for global clients across industries including healthcare, finance, and technology. Work directly with senior partners on high-impact engagements.',
    requirements: 'Top-tier academic record. Strong Excel and PowerPoint skills. Demonstrated leadership experience.',
    apply_url: 'https://mckinsey.com/careers', apply_email: null,
    deadline: '2025-01-15', tier: 'featured', is_featured: true, is_active: true, created_at: '2024-11-15',
    companies: { id: '7', name: 'McKinsey & Company', logo_url: 'https://logo.clearbit.com/mckinsey.com', website: 'https://mckinsey.com', description: 'Global management consulting firm.', industry: 'Consulting', created_at: '2024-01-01' },
  },
  {
    id: '8', company_id: '8', title: 'Editorial Intern', type: 'internship',
    industry: 'Media', location_type: 'hybrid', city: 'New York', state: 'NY',
    pay_rate: 20, pay_period: 'hourly',
    description: 'Join our newsroom and contribute to one of the world\'s most respected publications. Work with editors across beats including tech, politics, and culture.',
    requirements: 'Journalism, English, or Communications major. Strong writing portfolio required. Experience with CMS platforms preferred.',
    apply_url: 'https://nytimes.com/careers', apply_email: null,
    deadline: '2025-02-15', tier: 'standard', is_featured: false, is_active: true, created_at: '2024-11-20',
    companies: { id: '8', name: 'The New York Times', logo_url: 'https://logo.clearbit.com/nytimes.com', website: 'https://nytimes.com', description: 'Leading news organization and media company.', industry: 'Media', created_at: '2024-01-01' },
  },
]
